#!/usr/bin/env python3

import rospy
import actionlib
import tf

import sys
sys.path.insert(0, '/home/sergio/ur_ws/src/ur_pkg/src/functions')
from ur5_params import *
from ur_kinematics_functions import *

from sensor_msgs.msg import JointState
from control_msgs.msg import FollowJointTrajectoryAction, FollowJointTrajectoryGoal
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

# =============================================================
# Configuracion articular inicial (rad)
q = np.radians(np.array([90.0, -90.0, 90.0, -90.0, -90.0, 0.0]))

# Posicion deseada
#xd = np.array([-0.1017,  0.724,  0.341])
#xd = np.array([-0.1246,  0.6522,  0.5965])
xd = np.array([0.10415,  -0.7469,  0.236859])
if check_ur_ws(xd,r_ws) == True:
	print("Posicion deseada alcanzable")
else:
	print("Posicion deseada inalcanzable")

# Configuracion articular deseada (rad)
qdes = ikine(xd,q,l)
# =============================================================

q_real = np.zeros(6)

def callback(msg):

	global q_real
	
	q_real = msg.position
	q_real = np.asarray(q_real)
	q_real[[0,2]] = q_real[[2,0]]

if __name__ == '__main__':

	rospy.init_node("ur5_control_ikine", anonymous=True, disable_signals=True)
	
	rospy.Subscriber("/ur5_robot/joint_states", JointState, callback)
	
	tf_listener = tf.TransformListener()
	
	robot_client = actionlib.SimpleActionClient('/ur5_robot/scaled_pos_joint_traj_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
	#robot_client = actionlib.SimpleActionClient('/ur5_robot/pos_joint_traj_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
	print("Waiting for server...")
	robot_client.wait_for_server()
	print("Connected to server")

	joint_names = ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']

	#Configuracion articular inicial
	Q0 = q.tolist()

	g = FollowJointTrajectoryGoal()
	g.trajectory = JointTrajectory()
	g.trajectory.joint_names = joint_names

	# Posicion articular inicial
	g.trajectory.points = [ JointTrajectoryPoint(positions=Q0,time_from_start=rospy.Duration(1.0))]
	robot_client.send_goal(g)
	robot_client.wait_for_result()
	rospy.sleep(1)

	# Frecuencia del envio (en Hz)
	freq = 100
	rate = rospy.Rate(freq)
	# Tiempo de muestreo
	dt = 1.0/freq	
	t = 1.0 + dt

	#Se le asigna al Q0 la configuracion articular hallada
	Q0 = qdes.tolist()	

	g.trajectory.points = [JointTrajectoryPoint(positions=Q0,time_from_start=rospy.Duration(t))]
	robot_client.send_goal(g)

while not rospy.is_shutdown():

	t = t + dt

	# Esperar hasta la siguiente  iteracion
	rate.sleep()